<?php

namespace Logger\Service;

use Zend\Log\Logger as ZendLogger;

class LoggerService extends ZendLogger
{
    public function __construct($options = null)
    {
        echo "LoggerService::__construct"."<br/>";
        return parent::__construct($options); // TODO: Change the autogenerated stub
    }



    final public function log($priority, $message, $extra = array())
    {
        //$filename = 'log_' . date('Y-m-d') . '.txt';
        //$writer = new Stream('./data/logs/' . $filename);
        //$this->addWriter($writer);

        $customExtra = array(
            'Caprio\Logger' => array(
                'sessionId' => session_id(),
                'host'      => !empty($_SERVER['HTTP_HOST']) ? $_SERVER['HTTP_HOST'] : 'CLI',
                'ip'        => !empty($_SERVER['REMOTE_ADDR']) ? $_SERVER['REMOTE_ADDR'] : 'unavailable'
            )
        );


        return parent::log($priority,
                $message,
                array_merge($extra, $customExtra));
    }




} 